apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      name: kubia-pod
      labels:
        app: kubia
    spec:
      containers:      
      -  name: kubia-container
         image: blgreco72dev/kubia
         ports:
          - containerPort: 8080
