apiVersion:  apps/v1
kind: ReplicaSet
metadata:
  name: kube-service
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
      service: kube
  template:
    metadata:
      labels:
        type: backend
        service: kube
        db: mongo
        language: dotnet-core
    spec:
      containers:
      - name: kube-srv
        image: blgreco72dev/kube-service-1
        ports:
          - containerPort: 80
            protocol: TCP
