apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia-container
        image: blgreco72dev/kubia
