apiVersion: v1
kind: Pod
metadata:
  name: kube-service
spec:
  containers:
  - image: blgreco72dev/kube-service
    name: kube-srv
    ports:
    - containerPort: 6200
      protocol: TCP
    env:
      - name: value-one
        valueFrom:
          configMapKeyRef:
             name:  devconfig
             key: val1
      - name: value-two
        valueFrom:
          configMapKeyRef:
            name: devconfig
            key: val2
            
     
