apiVersion: v1
kind: Pod
metadata:
  name: kube-service
spec:
  containers:
  - image: blgreco72dev/kube-service
    name: kube-srv
    ports:
    - containerPort: 6200
      protocol: TCP
    envFrom:
    - prefix: CONFIG_
      configMapRef:
        name: devconfig
