apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kube-service-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-srv
  template:
    metadata:
      labels:
        app: kube-srv
    spec:
      containers:
      - name: kube-srv-container
        image: blgreco72dev/kube-service
        livenessProbe:
          httpGet:
            path: /api/pod/health-check
            port: 6200
        ports:
        - containerPort: 6200
