    apiVersion: v1
    kind: Service
    metadata:
      name: kube-service-np
    spec:
      type: NodePort
      ports:  
      - port: 80
        targetPort: 6200
        nodePort: 31490
      selector:
        app: kube-srv
