apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-service-rc
spec:
  replicas: 3
  selector:
    app: kube-srv
  template:
    metadata:
      name: kube-srv-pod
      labels:
        app: kube-srv
    spec:
      containers:      
      -  name: kube-srv-container
         image: blgreco72dev/kube-service
         ports:
          - containerPort: 6200
